chore:
  - changed-files:
      any-glob-to-any-file:
        - CHANGELOG.md
        - .gitignore
        - .prettierrc
        - package.json
        - bun.lock

ci:
  - changed-files:
      any-glob-to-any-file:
        - .github/workflows/**/*

documentation:
  - changed-files:
      any-glob-to-any-file:
        - README.md
        - docs/**/*

feature:
  - changed-files:
      any-glob-to-any-file:
        - app/**/*
        - components/**/*

content:
  - changed-files:
      any-glob-to-any-file:
        - content/**/*

config:
  - changed-files:
      any-glob-to-any-file:
        - "*.config.*"
        - tsconfig.json
        - components.json
        - .env.example
